version: "3.8"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - storage

  storage:
    build:
      context: ./storage
    volumes:
      - storage_data:/data

volumes:
  storage_data:
